### ISSUE TITLE
Step numbering is broken

### ISSUE THREAD

**Issue by johnmhoenig** [ibm-cloud-docs/bare-metal#17]
It seems there are 19 steps but the SAP note breaks the numbering and implies the last 9 steps are for SAP only.

**Comment by jmilst** [comment]
Hi @johnmhoenig. Would you mind sharing where you found this? Thanks!

**Comment by johnmhoenig** [comment]
https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-ordering-baremetal-server
