### ISSUE TITLE
List network port speeds available

### ISSUE THREAD

**Issue by InfoSec812** [ibm-cloud-docs/bare-metal#23]
The documentation for Bare Metal networking options does not make it clear what port speeds are available. Is there only 1Gbps and then you provide port bonding for higher bandwidth requirements?

https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-network-options

**Comment by jmilst** [comment]
Copied to https://jiracloud.swg.usma.ibm.com:8443/browse/CFD-355?workflowName=CFD+Workflow&stepId=1

Thanks for your input, Deven!
