### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by thowden** [ibm-cloud-docs/bare-metal#34]
Hi

Trying to resolve my servers showing as 'Disconnected' due to ping disabled in firewall. 

Link "For more information, see IBM Cloud® IP ranges."  is broken.

Please provide correct link to the "IBM Cloud® IP ranges." documentation.

**Comment by cvigliet** [comment]
**Page**: https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-troubleshooting-bare-metal#bm-troubleshoot-portal-shows-server-disconnected-but-running
**Topic**: https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-troubleshooting-bare-metal#bm-troubleshoot-portal-shows-server-disconnected-but-running
**Broken link**: IBM Cloud® IP ranges
https://cloud.ibm.com/docs/security-groups?topic=hardware-firewall-dedicated-ibm-cloud-ip-ranges
**Where we could be able to find the information**: https://cloud.ibm.com/docs/hardware-firewall-shared?topic=hardware-firewall-shared-ibm-cloud-ip-ranges **not sure if it was the same page**

**Comment by jmilst** [comment]
Thanks so much, @cvigliet. The link is now updated.
