### ISSUE TITLE
Bare Metal add-ons - Additional NICs missing (including price)

### ISSUE THREAD

**Issue by danieloflanagan** [ibm-cloud-docs/bare-metal#36]
I cannot find anywhere the List Price for an additional NIC port, added via a ticket after bare metal provisioning is complete.  Its not available to order with a Bare Metal Server, and has to be raised as a request after the Bare Metal Server has been provisioned, so please can someone add this important content (including the pricing so that users can understand the costs of adding the additional NIC ports).  It could be added in several places, but I thought here might be good - https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-about-bm#bm-add-ons.  It would be good to clarify that if you have a bare metal on private only NICs, whether an additional NIC can be on public or not too, so that people understand what they can do.

**Comment by jmilst** [comment]
Hi @danieloflanagan. Thanks for reaching out, but we don't include pricing information in the product documentation. You can find pricing information in [Billing and usage](https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-cost).
