### ISSUE TITLE
The WSUS servers in IBM Cloud work only with operating system patches.

### ISSUE THREAD

**Issue by tetsuofukuzaki** [ibm-cloud-docs/bare-metal#37]
The WSUS servers in IBM Cloud work only with operating system patches.
I recommend to modify the following description to make it clear that the WSUS servers in IBM Cloud does not provide the patches for Microsoft provided software such as Windows Defender, SQL Server and so on.
"IBM provides OS and software update services for Microsoft Windows Server environments free of charge."

**Comment by strakerpj** [comment]
Related to the WSUS updates page here: https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-updating-an-instance-to-use-a-local-wsus-server

There is no link to the list of local datacenter name formats that are valid.
It simply says `Change wsusdal0102 to the local data center where your server is provisioned.`

Having a link to the list of valid wsus DNS names would be helpful.
