### ISSUE TITLE
Reloading the OS should not be done for IBM Cloud for VMware Solutions ESXi hosts

### ISSUE THREAD

**Issue by yellton** [ibm-cloud-docs/bare-metal#45]
Hi... I work on IBM Cloud for VMware Solutions.  

Our [vCenter Server (VCS) offering](https://cloud.ibm.com/vmware/compare_offerings) orders an ESXi bare metal from the datacenter and then does _additional VMware configuration on the host_ to make the host part of a VMware cluster and add the host to an Active Directory Domain.

Reloading the OS sets the host configuration back to what it looked like when the datacenter finished configuring it.

That is, OS reload wipes out the additional IBM Cloud for Vmware Solutions VMware and domain configuration.   The host no longer functions properly in the VMware cluster.

Could you add a warning like this:

> Customers using the IBM Cloud for VMware Solutions vCenter Server (VCS) offering should not use the Reloading the OS option on ESXi bare metals that are part of a VCS instance.

to this page?: 
Reloading the OS
https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-reloading-the-os

Dorine Yelton
IBM Cloud for VMware Solutions DevOps
yelton@us.ibm.com

**Comment by jmilst** [comment]
Hi @yellton - added this note just under the Reloading the OS section:

 "If you use IBM Cloud for VMware Solutions vCenter Server (VCS), don't use the 'Reloading the OS' option on ESXi bare metal servers that are part of a VCS instance." with an "Important" callout tag. 

Thanks!
