### ISSUE TITLE
The information on these pages does not match.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/bare-metal#48]
Hello,

https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-product-lifecycle-classic#vrouter-classic
https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-product-lifecycle-vyatta

The information on these pages does not match. The VRA versions and EOS dates are different.
Perhaps the information in the first URL is out of date. Could you update the docs to provide consistent information?

Thank you,

**Comment by jmilst** [comment]
Updated https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-product-lifecycle-classic#vrouter-classic to align with https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-product-lifecycle-vyatta.

Thank you for the feedback @ytama.
