### ISSUE TITLE
Update the Lifecycle for operating systems and add-ons page with RHEL SAP and HANA info

### ISSUE THREAD

**Issue by sariethv** [ibm-cloud-docs/bare-metal#49]
Update the Red Hat Enterprise Linux (RHEL) table under Lifecycle for operating systems and add-ons page with following data.
The SAP and HANA details were missing from the RHEL table.
The classic life cycle page and VPC are totally different now, so would like to align them.

Classic - https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-product-lifecycle-classic
VPC - https://cloud.ibm.com/docs/vpc?topic=vpc-guest-os-lifecycle

RHEL 8.2 (SAP HANA and SAP applications) | 28 February 2023
RHEL 7.6 (SAP HANA and SAP applications) | 28 February 2023

**Comment by jmilst** [comment]
RHEL SAP added to Classic lifecycle page
