### ISSUE TITLE
TransactionID=240371b50000000028

### ISSUE THREAD

**Issue by jingru88** [ibm-cloud-docs/bare-metal#51]
Not sure why,  But I kept getting this error message, I've restarted the server but still not working. 

![image](https://github.com/user-attachments/assets/1c5bb577-f3e9-46f2-b9df-e48e9adfd5a2)

**Comment by jmilst** [comment]
Hi @jingru88. This GitHub is for documentation. Please reach out to support. 

https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-bare-metal-help-and-support
