### ISSUE TITLE
Please correct VRA version and EOS info in "Lifecycle for operating systems and add-ons"

### ISSUE THREAD

**Issue by ka7harada** [ibm-cloud-docs/bare-metal#54]
### **Request**
Please correct version # and its EOS date in "Lifecycle for operating systems and add-ons"

For correct date pls check this 
https://cloud.ibm.com/docs/virtual-router-appliance?topic=virtual-router-appliance-product-lifecycle-vyatta
<img width="661" alt="image" src="https://github.com/user-attachments/assets/cf86959f-7fd5-4f61-80c2-9d899f303629">

### **Urgency**
Soon as possible

### **Location:**
Operating system lifecycles>Ciena vRouter (Vyatta)
https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-product-lifecycle-classic&locale=en#vrouter-classic

### **Where to change**
**Correct**
Operating system | End of support
-- | --
2308 (available only on bare metal servers) | 18 February 2026

**Wrong**:
Operating system | End of support
-- | --
2208 (available only on bare metal servers) | 18 February 2025

**Comment by jmilst** [comment]
The change is published. Thank you @ka7harada.
